const fakeData = [
	{
		id: 1,
		name: 'Cursed Blade',
		type: 'Sword',
		rarity: 4,
		attack_power: 1200,
		element: 'Fire',
		crit_rate: 0.25,
		crit_damage: 1.8,
		effect_description: 'Deals increased damage to cursed enemies',
		level: 20,
		upgrade_cost: 15000,
		creation_date: '2022-03-15'
	},
	{
		id: 2,
		name: 'Haunted Greataxe',
		type: 'Axe',
		rarity: 5,
		attack_power: 1800,
		element: 'Dark',
		crit_rate: 0.18,
		crit_damage: 2.1,
		effect_description: 'Has a chance to curse enemies on hit',
		level: 25,
		upgrade_cost: 25000,
		creation_date: '2021-11-28'
	},
	{
		id: 3,
		name: 'Otherworldly Dagger',
		type: 'Dagger',
		rarity: 3,
		attack_power: 900,
		element: 'Arcane',
		crit_rate: 0.3,
		crit_damage: 1.5,
		effect_description: 'Teleports the user behind the target on critical hits',
		level: 15,
		upgrade_cost: 10000,
		creation_date: '2022-08-02'
	},
	{
		id: 4,
		name: 'Unholy Greatsword',
		type: 'Sword',
		rarity: 4,
		attack_power: 1600,
		element: 'Dark',
		crit_rate: 0.22,
		crit_damage: 1.9,
		effect_description: 'Drains life from enemies on hit',
		level: 22,
		upgrade_cost: 20000,
		creation_date: '2021-06-14'
	},
	{
		id: 5,
		name: 'Spectral Bow',
		type: 'Bow',
		rarity: 5,
		attack_power: 1700,
		element: 'Arcane',
		crit_rate: 0.2,
		crit_damage: 2.3,
		effect_description: 'Arrows pass through multiple enemies',
		level: 26,
		upgrade_cost: 28000,
		creation_date: '2022-01-05'
	},
	{
		id: 6,
		name: 'Abyssal Mace',
		type: 'Mace',
		rarity: 3,
		attack_power: 1100,
		element: 'Dark',
		crit_rate: 0.28,
		crit_damage: 1.6,
		effect_description: 'Chance to stun enemies on hit',
		level: 18,
		upgrade_cost: 12000,
		creation_date: '2021-09-22'
	},
	{
		id: 7,
		name: 'Cursed Scythe',
		type: 'Scythe',
		rarity: 4,
		attack_power: 1400,
		element: 'Dark',
		crit_rate: 0.24,
		crit_damage: 2.0,
		effect_description: 'Deals increased damage to cursed enemies',
		level: 21,
		upgrade_cost: 18000,
		creation_date: '2022-04-30'
	},
	{
		id: 8,
		name: 'Infernal Scepter',
		type: 'Staff',
		rarity: 5,
		attack_power: 1900,
		element: 'Fire',
		crit_rate: 0.19,
		crit_damage: 2.2,
		effect_description: 'Periodically inflicts the target with a cursed burn effect',
		level: 27,
		upgrade_cost: 30000,
		creation_date: '2021-12-10'
	},
	{
		id: 9,
		name: 'Haunted Crossbow',
		type: 'Crossbow',
		rarity: 3,
		attack_power: 1000,
		element: 'Dark',
		crit_rate: 0.32,
		crit_damage: 1.4,
		effect_description: 'Arrows have a chance to ricochet and hit additional targets',
		level: 16,
		upgrade_cost: 11000,
		creation_date: '2022-07-18'
	},
	{
		id: 10,
		name: 'Cursed Cannon',
		type: 'Cannon',
		rarity: 4,
		attack_power: 1500,
		element: 'Dark',
		crit_rate: 0.21,
		crit_damage: 2.1,
		effect_description: 'Deals increased damage to heavily armored enemies',
		level: 23,
		upgrade_cost: 22000,
		creation_date: '2021-08-03'
	}
];

export default fakeData;
